# Generated by Django 5.2.4 on 2025-08-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_account_id_alter_user_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', '처리 대기'), ('resolved', '처리 완료'), ('rejected', '무시됨')], default='pending', max_length=10),
        ),
    ]
