# Generated by Django 5.2.4 on 2025-08-05 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_follow_follower_alter_follow_following_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ['-created_at']},
        ),
    ]
