# Generated by Django 5.2.4 on 2025-08-06 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_follow_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
