# Generated by Django 5.2.4 on 2025-08-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('잎채소류', '잎채소류'), ('열매채소류', '열매채소류'), ('뿌리채소류', '뿌리채소류'), ('과일류', '과일류'), ('곡류·잡곡', '곡류·잡곡'), ('버섯류', '버섯류'), ('견과류', '견과류'), ('기타농산물', '기타농산물'), ('생선류', '생선류'), ('갑각류', '갑각류'), ('조개류', '조개류'), ('연체류', '연체류'), ('건어물류', '건어물류'), ('젓갈류', '젓갈류'), ('어패가공품', '어패가공품'), ('기타수산물', '기타수산물')], max_length=100, unique=True)),
                ('type', models.CharField(choices=[('agricultural', '농산물'), ('fishing', '수산물')], max_length=20)),
                ('icon_image', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
